Drop macOS 14 from tests, specify Xcode version
A mismatched Xcode version on GitHub's macOS 14 GitHub Actions image appears to be causing this failure:

```
  Warning: You have uncommitted modifications to Homebrew/homebrew-core.
  If this is a surprise to you, then you should stash these modifications.
  Stashing returns Homebrew to a pristine state but can be undone
  should you later need to do so for some reason.
    git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" stash -u && git -C "/opt/homebrew/Library/Taps/homebrew/homebrew-core" clean -d -f

  Uncommitted files:
    ?? Formula/o/openssl@1.1.rb

Error: 1 failed step!
```

See https://github.com/Homebrew/homebrew-core/issues/228131#issuecomment-3182150180 and https://github.com/actions/runner-images/issues/13275.

We've decided that macOS 14 and 15 are similar enough that we can drop macOS 14 from being tested (at least for now).

Signed-off-by: risc <risc@fastmail.com>